DE-6498: Storybook
castlabs/prestoplay-react-components pull request #12
Opened 2023-07-10 14:10 UTC by fingerartur

Added storybook for API docs and development of the components.

Here I also did a few drive-by fixes of some bugs and the API, but more will come in [DE-6506](https://castlabs.atlassian.net/browse/DE-6506). There I will also fix the rest of the stories, bc. some of them currently do not work.

2023-07-11 09:54 UTC, fingerartur commented
Okay, I fixed the Jest config, now it's really ready for review :)

2023-10-05 18:36 UTC, doubeka requested changes
This is such an great improvement of this documentation on these components, great job 💯 
I left few comments, mostly related to docs. 
Some additional extended descriptions for components in stories, when it makes (IMO) sense, some of the others may need another pass later and update even examples. (like spacer). 
I also checked the followup ticket, and I am happy to help and do some work on some following updates and improvements on various components APIs.  I would propose to schedule some planning session to flesh that plan furter.

2023-10-05 18:36 UTC, doubeka commented on story/stories/components/TimeLeft.mdx
> +Time left.
```suggestion
A component to show the remaining playback duration.
```

2023-10-05 18:36 UTC, doubeka commented on story/stories/components/VolumeBar.mdx
> +Volume bar.
```suggestion
A component to increase/decrease volume by dragging the slider.
```

2023-10-09 06:29 UTC, fingerartur commented
Thanks!

2023-10-09 08:56 UTC, doubeka approved these changes

2023-10-09 09:49 UTC, merged